openapi: 3.1.0
info:
  title: OpenAPI Sample
  version: 1.0.0

paths:
  "/":
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"

    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Item"
      responses:
        "201":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /items:
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Item"
  /items/{id}:
    get:
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
  /items/first5{format}:
    get:
      parameters:
      - name: format
        in: path
        required: true
        schema:
          type: string
          pattern: '(.(xml|json))?'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Item"
components:
  schemas:
    Item:
      type: object
      unevaluatedProperties: false
      required: [foo]
      properties:
        foo:
          type: string
          enum: [bar, baz, qux, quux, corge, grault, garply, waldo, fred, plugh, xyzzy, thud]
    Error:
      type: object
      unevaluatedProperties: false
      required: [message]
      properties:
        message:
          type: string
    IntegerString:
      type: string
      pattern: '\d+'
  parameters:
    id:
      name: id
      in: path
      required: true
      schema:
        $ref: "#/components/schemas/IntegerString"
