name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Linter
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true
      - name: Run StandardRB
        run: bundle exec standardrb

  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
    strategy:
      matrix:
        ruby:
          - "3.3"
          - "3.2"
          - "3.1"
          - "3.0"
          - "2.7"
          - "jruby"
          - "truffleruby"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run RSpec
        run: bundle exec rspec
      - name: Run RSpec examples
        run: CI=1 ruby examples/rspec.rb
      - name: Fix RubyGems activating older versions of gems
        run: gem install timeout net-protocol stringio psych date
      - name: Run RSpec Rails examples
        run: CI=1 ruby examples/rspec_rails.rb
      - name: Run minitest example
        run: CI=1 ruby examples/minitest.rb
