name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

env:
  CI: 1

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Linter
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true
      - name: Run StandardRB
        run: bundle exec standardrb

  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
    strategy:
      matrix:
        ruby:
          - "3.3"
          - "3.2"
          - "3.1"
          - "3.0"
          - "2.7"
          - "jruby"
          - "truffleruby"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run RSpec
        run: bundle exec rspec
      - name: Install RSpec example dependencies
        run: bundle install --gemfile ./examples/Gemfile-rspec
      - name: Run RSpec example
        run: bundle exec --gemfile ./examples/Gemfile-rspec ruby examples/rspec.rb
      - name: Install minitest example dependencies
        run: bundle install --gemfile ./examples/Gemfile-minitest
      - name: Run minitest example
        run: bundle exec --gemfile ./examples/Gemfile-minitest ruby examples/minitest.rb
      - name: Run RSpec Rails example
        working-directory: ./examples/rails_app
        run: |
          bundle install
          bundle exec rspec
